### ISSUE TITLE
[question] How my app can call `wallet.get_address()` ?

### ISSUE THREAD

**Issue by monaka** [RGB-Tools/rgb-lib#22] opened 2022-12-22 04:46 UTC
I got an issue when I accessed the `Wallet` object.
I see what the error message means.
And I think `wallet` can't be static because `wallet` is instantiated from `WalletData`. 
Cloud you give me some hints on how to call `wallet.get_address()` from async functions? 

The full code tree is https://github.com/diamondhands-dev/shiro-backend/tree/90db825b982e286e8a630d59a97aa1d781f394e3.   
Related code and logs are below.

```
    pub async fn new_address(&mut self) -> Result<String, rgb_lib::Error> {
        match self.new_wallet().await {
            Ok(_) => (),
            Err(err) => return Err(err),
        }
        match self {
            Self::WalletDataE(_) => Err(rgb_lib::Error::Inconsistency("".to_string())),
            Self::WalletE(wallet) => match Self::_new_address(wallet).await {
                Ok(address) => Ok(address),
                Err(err) => Err(rgb_lib::Error::Inconsistency("new_address".to_string())),
            }
        }
    }

    async fn _new_address(wallet: &mut Wallet) -> Result<String, actix_web::rt::task::JoinError> {
        actix_web::rt::task::spawn_blocking(move || wallet.get_address()).await
    }
```

it was build failure.

```
error[E0521]: borrowed data escapes outside of associated function
   --> src/wallet.rs:117:9
    |
116 |     async fn _new_address(wallet: &mut Wallet) -> Result<String, actix_web::rt::task::JoinError> {
    |                           ------  - let's call the lifetime of this reference `'1`
    |                           |
    |                           `wallet` is a reference that is only valid in the associated function body
117 |         actix_web::rt::task::spawn_blocking(move || wallet.get_address()).await
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |         |
    |         `wallet` escapes the associated function body here
    |         argument requires that `'1` must outlive `'static`
```

**Comment by zoedberg** [comment] 2022-12-22 12:26
I tried running tests on https://github.com/diamondhands-dev/shiro-backend/tree/90db825b982e286e8a630d59a97aa1d781f394e3 but I receive several errors:

```
error[E0425]: cannot find value `online` in this scope
  --> src/wallet/utxos.rs:28:51
   |
28 |                 num_utxos_created: _utxos(wallet, online, params.into_inner()).await.unwrap(),
   |                                                   ^^^^^^ not found in this scope

error[E0412]: cannot find type `WalletState` in this scope
  --> src/main.rs:48:54
   |
48 |         pub(crate) fn get_wallet_state(&mut self) -> WalletState {
   |                                                      ^^^^^^^^^^^ not found in this scope
   |
help: consider importing this enum
   |
30 |     use crate::wallet::WalletState;
   |

warning: unused import: `std::fmt`
 --> src/wallet.rs:5:5
  |
5 | use std::fmt;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `body::to_bytes`
  --> src/wallet/utxos.rs:52:21
   |
52 |     use actix_web::{body::to_bytes, http, test, web, App};
   |                     ^^^^^^^^^^^^^^

error[E0521]: borrowed data escapes outside of associated function
   --> src/wallet.rs:117:9
    |
116 |     async fn _new_address(wallet: &mut Wallet) -> Result<String, actix_web::rt::task::JoinError> {
    |                           ------  - let's call the lifetime of this reference `'1`
    |                           |
    |                           `wallet` is a reference that is only valid in the associated function body
117 |         actix_web::rt::task::spawn_blocking(move || { wallet.get_address() }).await
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |         |
    |         `wallet` escapes the associated function body here
    |         argument requires that `'1` must outlive `'static`

error[E0308]: mismatched types
  --> src/wallet/utxos.rs:28:43
   |
28 |                 num_utxos_created: _utxos(wallet, online, params.into_inner()).await.unwrap(),
   |                                    ------ ^^^^^^ expected struct `Wallet`, found `()`
   |                                    |
   |                                    arguments to this function are incorrect
   |
note: function defined here
  --> src/wallet/utxos.rs:42:10
   |
42 | async fn _utxos(mut wallet: Wallet, online: Online, params: UtxosParams) -> Result<u8, rgb_lib::Error> {
   |          ^^^^^^ ------------------

Some errors have detailed explanations: E0308, E0412, E0425, E0521.
For more information about an error, try `rustc --explain E0308`.
warning: `shiro-backend` (bin "shiro-backend" test) generated 2 warnings
error: could not compile `shiro-backend` due to 4 previous errors; 2 warnings emitted
warning: build failed, waiting for other jobs to finish...
```

@monaka could you please fix the other errors so that we can be sure the issue is actually with `get_address`?

**Comment by monaka** [comment] 2022-12-23 00:44
I cleaned up (remove warning and other errors) and re-pushed.

https://github.com/diamondhands-dev/shiro-backend/tree/c4c4827c4b5fa3a0b7dded1b139bf9e34c255456

I guess it can avoid if we could use Tokio's `block_in_place()`.
But we can't use it with actix-web ( https://docs.rs/actix-web/latest/actix_web/rt/index.html#fn1 )

**Comment by zoedberg** [comment] 2022-12-23 13:57
I've tried to remove the line giving errors, changing it with something compatible with the method signature:
```diff
async fn _new_address(wallet: &mut Wallet) -> Result<String, actix_web::rt::task::JoinError> {
-    actix_web::rt::task::spawn_blocking(move || wallet.get_address()).await
+    Ok("fake_address".to_string())
}
```

and doing so I've discovered a lot of other errors that need to be fixed first:

```
warning: unused import: `std::fmt`
 --> src/wallet.rs:5:5
  |
5 | use std::fmt;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unreachable pattern
  --> src/wallet.rs:97:13
   |
97 |             _ => None,
   |             ^
   |
   = note: `#[warn(unreachable_patterns)]` on by default

error[E0004]: non-exhaustive patterns: `&mut None` not covered
   --> src/wallet.rs:123:23
    |
123 |                 match options {
    |                       ^^^^^^^ pattern `&mut None` not covered
    |
note: `std::option::Option<WalletData>` defined here
   --> /home/zoe/snap/rustup/common/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:522:5
    |
518 | pub enum Option<T> {
    | ------------------
...
522 |     None,
    |     ^^^^ not covered
    = note: the matched value is of type `&mut std::option::Option<WalletData>`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
132 ~                     }
133 ~                     &mut None => todo!(),
    |

warning: unused variable: `err`
  --> src/wallet/address.rs:21:17
   |
21 |             Err(err) => HttpResponse::BadRequest().body("a"),
   |                 ^^^ help: if this is intentional, prefix it with an underscore: `_err`
   |
   = note: `#[warn(unused_variables)]` on by default

warning: unused variable: `wallet_data`
  --> src/wallet.rs:72:31
   |
72 |             Self::WalletDataE(wallet_data) => {
   |                               ^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_wallet_data`

warning: unused variable: `err`
   --> src/wallet.rs:110:21
    |
110 |                 Err(err) => Err(rgb_lib::Error::Inconsistency("new_address".to_string())),
    |                     ^^^ help: if this is intentional, prefix it with an underscore: `_err`

warning: unused variable: `wallet`
   --> src/wallet.rs:115:27
    |
115 |     async fn _new_address(wallet: &mut Wallet) -> Result<String, actix_web::rt::task::JoinError> {
    |                           ^^^^^^ help: if this is intentional, prefix it with an underscore: `_wallet`

warning: unused variable: `wallet`
   --> src/wallet.rs:135:27
    |
135 |             Self::WalletE(wallet) => Ok(()),
    |                           ^^^^^^ help: if this is intentional, prefix it with an underscore: `_wallet`

warning: unused variable: `wallet_data`
   --> src/wallet.rs:179:18
    |
179 |             Some(wallet_data) => HttpResponse::Ok().json(params),
    |                  ^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_wallet_data`

error[E0507]: cannot move out of `self.wallet_state` which is behind a shared reference
  --> src/wallet.rs:25:9
   |
25 |         self.wallet_state
   |         ^^^^^^^^^^^^^^^^^ move occurs because `self.wallet_state` has type `wallet::WalletState`, which does not implement the `Copy` trait

error[E0507]: cannot move out of `self.online` which is behind a shared reference
  --> src/wallet.rs:28:9
   |
28 |         self.online
   |         ^^^^^^^^^^^ move occurs because `self.online` has type `std::option::Option<Online>`, which does not implement the `Copy` trait

error: lifetime may not live long enough
  --> src/main.rs:46:13
   |
45 |         pub(crate) fn get_shiro_wallet(&mut self) -> MutexGuard<'static, ShiroWallet> {
   |                                        - let's call the lifetime of this reference `'1`
46 |             self.shiro_wallet.lock().unwrap()
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ returning this value requires that `'1` must outlive `'static`

error[E0507]: cannot move out of dereference of `std::sync::MutexGuard<'_, wallet::ShiroWallet>`
  --> src/main.rs:49:13
   |
49 |             self.shiro_wallet.lock().unwrap().wallet_state
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because value has type `wallet::WalletState`, which does not implement the `Copy` trait

error[E0507]: cannot move out of dereference of `once_cell::sync::Lazy<std::sync::Mutex<wallet::ShiroWallet>>`
  --> src/main.rs:64:31
   |
64 |                 shiro_wallet: *SHIRO_WALLET,
   |                               ^^^^^^^^^^^^^ move occurs because value has type `std::sync::Mutex<wallet::ShiroWallet>`, which does not implement the `Copy` trait

Some errors have detailed explanations: E0004, E0507.
For more information about an error, try `rustc --explain E0004`.
warning: `shiro-backend` (bin "shiro-backend" test) generated 8 warnings
error: could not compile `shiro-backend` due to 6 previous errors; 8 warnings emitted
```

@monaka From the error logs it seems you're still having issues in sharing the wallet instance correctly. I believe we cannot debug `get_address` until that part gets fixed.

**Comment by zoedberg** [comment] 2022-12-27 14:14
@monaka Closing this since https://github.com/diamondhands-dev/shiro-backend/pull/48 should show that it's possible to call `get_address` in an async environment without any changes to rgb-lib

**Closed by zoedberg** 2022-12-27 14:14 UTC
